
// THIS FILE IS AUTOGENERATED WHEN PAGES ARE UPDATED
import { lazy } from "react";
import { RouteObject } from "react-router-dom";




const AIStaffManagementHub = lazy(() => import("./pages/AIStaffManagementHub.tsx"));
const AppDeployment = lazy(() => import("./pages/AppDeployment.tsx"));
const About = lazy(() => import("./pages/About.tsx"));
const Admin = lazy(() => import("./pages/Admin.tsx"));
const AllOrders = lazy(() => import("./pages/AllOrders.tsx"));
const App = lazy(() => import("./pages/App.tsx"));
const CheckoutPayment = lazy(() => import("./pages/CheckoutPayment.tsx"));
const Contact = lazy(() => import("./pages/Contact.tsx"));
const CustomerPortal = lazy(() => import("./pages/CustomerPortal.tsx"));
const ForgotPassword = lazy(() => import("./pages/ForgotPassword.tsx"));
const Gallery = lazy(() => import("./pages/Gallery.tsx"));
const GeminiVoiceLab = lazy(() => import("./pages/GeminiVoiceLab.tsx"));
const HealthMonitor = lazy(() => import("./pages/HealthMonitor.tsx"));
const KDS_V2 = lazy(() => import("./pages/KDS_V2.tsx"));
const Login = lazy(() => import("./pages/Login.tsx"));
const MediaLibrary = lazy(() => import("./pages/MediaLibrary.tsx"));
const NotFoundPage = lazy(() => import("./pages/NotFoundPage.tsx"));
const OnlineOrders = lazy(() => import("./pages/OnlineOrders.tsx"));
const POSDesktop = lazy(() => import("./pages/POSDesktop.tsx"));
const POSLogin = lazy(() => import("./pages/POSLogin.tsx"));
const POSSettings = lazy(() => import("./pages/POSSettings.tsx"));
const PrinterManagement = lazy(() => import("./pages/PrinterManagement.tsx"));
const Reconciliation = lazy(() => import("./pages/Reconciliation.tsx"));
const SharedFavoritesList = lazy(() => import("./pages/SharedFavoritesList.tsx"));
const SignUp = lazy(() => import("./pages/SignUp.tsx"));
const ThermalReceiptDesignerV2 = lazy(() => import("./pages/ThermalReceiptDesignerV2.tsx"));
const Unauthorized = lazy(() => import("./pages/Unauthorized.tsx"));
const UpdateKDS = lazy(() => import("./pages/UpdateKDS.tsx"));
const UpdatePOSDesktop = lazy(() => import("./pages/UpdatePOSDesktop.tsx"));
const WebsiteManagement = lazy(() => import("./pages/WebsiteManagement.tsx"));
export const userRoutes: RouteObject[] = [



	{ path: "/ai-staff-management-hub", element: <AIStaffManagementHub />},
	{ path: "/app-deployment", element: <AppDeployment />},
	{ path: "/appdeployment", element: <AppDeployment />},
	{ path: "/aistaffmanagementhub", element: <AIStaffManagementHub />},
	{ path: "/about", element: <About />},
	{ path: "/admin", element: <Admin />},
	{ path: "/all-orders", element: <AllOrders />},
	{ path: "/allorders", element: <AllOrders />},
	{ path: "/", element: <App />},
	{ path: "/checkout-payment", element: <CheckoutPayment />},
	{ path: "/checkoutpayment", element: <CheckoutPayment />},
	{ path: "/contact", element: <Contact />},
	{ path: "/customer-portal", element: <CustomerPortal />},
	{ path: "/customerportal", element: <CustomerPortal />},
	{ path: "/forgot-password", element: <ForgotPassword />},
	{ path: "/forgotpassword", element: <ForgotPassword />},
	{ path: "/gallery", element: <Gallery />},
	{ path: "/gemini-voice-lab", element: <GeminiVoiceLab />},
	{ path: "/geminivoicelab", element: <GeminiVoiceLab />},
	{ path: "/health-monitor", element: <HealthMonitor />},
	{ path: "/healthmonitor", element: <HealthMonitor />},
	{ path: "/kds-v2", element: <KDS_V2 />},
	{ path: "/kds_v2", element: <KDS_V2 />},
	{ path: "/login", element: <Login />},
	{ path: "/media-library", element: <MediaLibrary />},
	{ path: "/medialibrary", element: <MediaLibrary />},
	{ path: "/not-found-page", element: <NotFoundPage />},
	{ path: "/notfoundpage", element: <NotFoundPage />},
	{ path: "/online-orders", element: <OnlineOrders />},
	{ path: "/onlineorders", element: <OnlineOrders />},
	{ path: "/pos-desktop", element: <POSDesktop />},
	{ path: "/posdesktop", element: <POSDesktop />},
	{ path: "/pos-login", element: <POSLogin />},
	{ path: "/poslogin", element: <POSLogin />},
	{ path: "/pos-settings", element: <POSSettings />},
	{ path: "/possettings", element: <POSSettings />},
	{ path: "/printer-management", element: <PrinterManagement />},
	{ path: "/printermanagement", element: <PrinterManagement />},
	{ path: "/reconciliation", element: <Reconciliation />},
	{ path: "/shared-favorites-list", element: <SharedFavoritesList />},
	{ path: "/sharedfavoriteslist", element: <SharedFavoritesList />},
	{ path: "/sign-up", element: <SignUp />},
	{ path: "/signup", element: <SignUp />},
	{ path: "/thermal-receipt-designer-v2", element: <ThermalReceiptDesignerV2 />},
	{ path: "/thermalreceiptdesignerv2", element: <ThermalReceiptDesignerV2 />},
	{ path: "/unauthorized", element: <Unauthorized />},
	{ path: "/update-kds", element: <UpdateKDS />},
	{ path: "/updatekds", element: <UpdateKDS />},
	{ path: "/update-pos-desktop", element: <UpdatePOSDesktop />},
	{ path: "/updateposdesktop", element: <UpdatePOSDesktop />},
	{ path: "/website-management", element: <WebsiteManagement />},

];
