name: Build and Release Cottage POS

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to release (e.g., 2.0.1)'
        required: false

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: windows-latest
    timeout-minutes: 45

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build application
        run: npm run build

      - name: Build and publish Windows installer
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm run build:publish

      - name: Upload installer as artifact (backup)
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: cottage-pos-installer-v${{ github.ref_name }}
          path: |
            dist/*.exe
            dist/*.nsis.7z
          retention-days: 90

      - name: Verify release created
        run: |
          echo "✅ Build completed successfully"
          echo "📦 Installer should be published to GitHub Releases"
          echo "🏷️ Tag: ${{ github.ref_name }}"
