name: Build and Release Windows Installer

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      version:
        description: 'Version number (e.g., 1.2.1)'
        required: false
        default: '1.2.1'

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Build and package Windows installer
      env:
        GH_TOKEN: ${{ secrets.COTTAGE_POS_PERSONAL_TOKEN }}
        GITHUB_TOKEN: ${{ secrets.COTTAGE_POS_PERSONAL_TOKEN }}
      run: |
        npm run build
        npm run release

    - name: Upload installer as backup artifact
      uses: actions/upload-artifact@v4
      with:
        name: cottage-tandoori-pos-installer
        path: dist/*.exe
        retention-days: 30

    - name: Create Release (if manual trigger)
      if: github.event_name == 'workflow_dispatch'
      uses: softprops/action-gh-release@v1
      with:
        tag_name: v${{ github.event.inputs.version }}
        name: Cottage Tandoori POS v${{ github.event.inputs.version }}
        files: dist/*.exe
        draft: false
        prerelease: false
        generate_release_notes: true
      env:
        GITHUB_TOKEN: ${{ secrets.COTTAGE_POS_PERSONAL_TOKEN }}