name: Build Cottage POS (Test)

on:
  push:
    tags:
      - 'v*-test*'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 30

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Delete existing package-lock.json
        run: |
          if (Test-Path package-lock.json) { Remove-Item package-lock.json -Force }

      - name: Install dependencies and regenerate lock file
        run: npm install

      - name: Verify build scripts exist
        run: |
          echo "Checking package.json scripts..."
          npm run --silent

      - name: Build application (test only)
        run: npm run build

      - name: Verify build output
        run: |
          echo "Build completed successfully!"
          if (Test-Path dist) { 
            echo "dist folder created"
            Get-ChildItem dist -ErrorAction SilentlyContinue
          }
