name: Publish Electron Assets on Release

on:
  release:
    types: [published]

permissions:
  contents: write
  actions: read

jobs:
  publish-assets:
    runs-on: windows-latest
    timeout-minutes: 60

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'

    - name: Install dependencies
      run: yarn install

    - name: Build and publish Electron app
      run: yarn run dist --publish always
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Verify artifacts created
      shell: bash
      run: |
        echo "Checking dist folder contents..."
        ls -la dist/ || echo "No dist folder found"

        echo "Looking for Windows artifacts..."
        find dist/ -name "*.exe" -o -name "latest.yml" -o -name "*.blockmap" || echo "No Windows artifacts found"
