name: Publish Electron Assets on Release

on:
  release:
    types: [published]

permissions:
  contents: write
  actions: read

jobs:
  publish-assets:
    runs-on: windows-latest
    timeout-minutes: 60

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'

    - name: Install dependencies
      run: yarn install

    - name: Build and publish Electron app
      run: yarn run publish
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        CI: true

    - name: Debug - Check if files were created
      shell: bash
      run: |
        echo "=== DIST FOLDER CONTENTS ==="
        ls -la dist/ 2>/dev/null || echo "No dist folder"

        echo "=== LOOKING FOR ARTIFACTS ==="
        find . -name "*.exe" -o -name "latest.yml" -o -name "*.blockmap" 2>/dev/null || echo "No artifacts found"

        echo "=== GITHUB RELEASE INFO ==="
        echo "Release tag: ${{ github.event.release.tag_name }}"
        echo "Release name: ${{ github.event.release.name }}"
