/**
 * SortableVariantRow Component
 * 
 * Draggable table row for variant grid with inline editing.
 * Integrates with @dnd-kit for smooth drag-and-drop reordering.
 * 
 * Features:
 * - Drag handle for reordering
 * - Inline editable cells (name, prices)
 * - Default variant selection (radio button)
 * - Delete action
 * - Visual feedback during drag
 */

import React from 'react';
import { useSortable } from '@dnd-kit/sortable';
import { CSS } from '@dnd-kit/utilities';
import { TableRow, TableCell } from '@/components/ui/table';
import { Button } from '@/components/ui/button';
import { EditableTableCell } from './EditableTableCell';
import { GripVertical, Trash2 } from 'lucide-react';
import { cn } from '@/lib/utils';
import type { ItemVariant } from 'utils/menuTypes';

interface SortableVariantRowProps {
  variant: Partial<ItemVariant>;
  index: number;
  editingCell: { row: number; col: string } | null;
  onEdit: (row: number, col: string) => void;
  onUpdate: (field: keyof ItemVariant, value: string | number | boolean) => void;
  onDelete: () => void;
  onSetDefault: () => void;
  isDuplicate?: boolean;
  defaultVariantId?: string;
}

export const SortableVariantRow: React.FC<SortableVariantRowProps> = ({
  variant,
  index,
  editingCell,
  onEdit,
  onUpdate,
  onDelete,
  onSetDefault,
  isDuplicate = false,
  defaultVariantId,
}) => {
  const {
    attributes,
    listeners,
    setNodeRef,
    transform,
    transition,
    isDragging,
  } = useSortable({ id: variant.id || `variant-${index}` });

  const style = {
    transform: CSS.Transform.toString(transform),
    transition,
  };

  // Helper to check if a cell is being edited
  const isCellEditing = (col: string) => {
    return editingCell?.row === index && editingCell?.col === col;
  };

  // Get prices with fallbacks
  const dineInPrice = variant.price_dine_in ?? variant.price ?? 0;
  const takeawayPrice = variant.price ?? 0;
  const deliveryPrice = variant.price_delivery ?? variant.price ?? 0;

  // Get display name - prefer auto-generated variant_name over manual name
  // variant_name is auto-generated by DB trigger: "{Protein} {Item Name}"
  // Fallback to variant.name for backwards compatibility
  // 🔍 DEBUG: Log variant structure to verify variant_name presence
  console.log('🔍 [VARIANT ROW DEBUG]', {
    variant_id: variant.id,
    has_variant_name: 'variant_name' in variant,
    variant_name_value: variant.variant_name,
    has_name: 'name' in variant,
    name_value: variant.name,
    all_keys: Object.keys(variant)
  });
  const displayName = variant.variant_name || variant.name || '';

  return (
    <TableRow
      ref={setNodeRef}
      style={style}
      className={cn(
        'group transition-all',
        isDragging && 'opacity-50 bg-purple-500/10',
        isDuplicate && 'bg-red-900/20 border-l-4 border-red-500',
        variant.is_default && 'bg-green-900/10'
      )}
    >
      {/* Drag Handle */}
      <TableCell
        className="w-12 cursor-grab active:cursor-grabbing"
        {...attributes}
        {...listeners}
      >
        <GripVertical className="h-4 w-4 text-gray-400 hover:text-gray-200 transition-colors" />
      </TableCell>

      {/* Variant Name - Display auto-generated full name */}
      <EditableTableCell
        value={displayName}
        type="text"
        isEditing={isCellEditing('name')}
        onEdit={() => onEdit(index, 'name')}
        onSave={(value) => onUpdate('name', value)}
        onCancel={() => onEdit(-1, '')}
        placeholder="Variant name..."
        className={cn(
          isDuplicate && 'border-l-2 border-red-500'
        )}
      />

      {/* Dine-In Price */}
      <EditableTableCell
        value={dineInPrice}
        type="currency"
        isEditing={isCellEditing('price_dine_in')}
        onEdit={() => onEdit(index, 'price_dine_in')}
        onSave={(value) => onUpdate('price_dine_in', Number(value))}
        onCancel={() => onEdit(-1, '')}
        min={0}
        max={999.99}
      />

      {/* Takeaway Price */}
      <EditableTableCell
        value={takeawayPrice}
        type="currency"
        isEditing={isCellEditing('price')}
        onEdit={() => onEdit(index, 'price')}
        onSave={(value) => onUpdate('price', Number(value))}
        onCancel={() => onEdit(-1, '')}
        min={0}
        max={999.99}
      />

      {/* Delivery Price */}
      <EditableTableCell
        value={deliveryPrice}
        type="currency"
        isEditing={isCellEditing('price_delivery')}
        onEdit={() => onEdit(index, 'price_delivery')}
        onSave={(value) => onUpdate('price_delivery', Number(value))}
        onCancel={() => onEdit(-1, '')}
        min={0}
        max={999.99}
      />

      {/* Dietary Toggles */}
      <TableCell className="w-16 text-center">
        <input
          type="checkbox"
          checked={variant.is_vegetarian ?? false}
          onChange={(e) => onUpdate('is_vegetarian', e.target.checked)}
          className="h-4 w-4 cursor-pointer accent-green-500"
          title="Vegetarian"
        />
      </TableCell>

      <TableCell className="w-16 text-center">
        <input
          type="checkbox"
          checked={variant.is_vegan ?? false}
          onChange={(e) => onUpdate('is_vegan', e.target.checked)}
          className="h-4 w-4 cursor-pointer accent-green-500"
          title="Vegan"
        />
      </TableCell>

      <TableCell className="w-16 text-center">
        <input
          type="checkbox"
          checked={variant.is_gluten_free ?? false}
          onChange={(e) => onUpdate('is_gluten_free', e.target.checked)}
          className="h-4 w-4 cursor-pointer accent-amber-500"
          title="Gluten-Free"
        />
      </TableCell>

      <TableCell className="w-16 text-center">
        <input
          type="checkbox"
          checked={variant.is_halal ?? false}
          onChange={(e) => onUpdate('is_halal', e.target.checked)}
          className="h-4 w-4 cursor-pointer accent-blue-500"
          title="Halal"
        />
      </TableCell>

      <TableCell className="w-16 text-center">
        <input
          type="checkbox"
          checked={variant.is_dairy_free ?? false}
          onChange={(e) => onUpdate('is_dairy_free', e.target.checked)}
          className="h-4 w-4 cursor-pointer accent-purple-500"
          title="Dairy-Free"
        />
      </TableCell>

      <TableCell className="w-16 text-center">
        <input
          type="checkbox"
          checked={variant.is_nut_free ?? false}
          onChange={(e) => onUpdate('is_nut_free', e.target.checked)}
          className="h-4 w-4 cursor-pointer accent-orange-500"
          title="Nut-Free"
        />
      </TableCell>

      {/* Spice Level Dropdown */}
      <TableCell className="min-w-[120px] text-center">
        <select
          value={variant.spice_level ?? ''}
          onChange={(e) => onUpdate('spice_level', e.target.value ? Number(e.target.value) : null)}
          className="w-full px-2 py-1 bg-gray-800 border border-gray-600 rounded text-sm text-gray-200 cursor-pointer hover:border-gray-500"
          title="Spice Level"
        >
          <option value="">None</option>
          <option value="0">0 - None</option>
          <option value="1">1 - Mild 🌶️</option>
          <option value="2">2 - Medium 🌶️🌶️</option>
          <option value="3">3 - Hot 🌶️🌶️🌶️</option>
          <option value="4">4 - Very Hot 🔥</option>
          <option value="5">5 - Extra Hot 🔥🔥</option>
          <option value="6">6 - Extreme 🔥🔥🔥</option>
        </select>
      </TableCell>

      {/* Allergens - Display as badges (click to edit in future) */}
      <TableCell className="min-w-[200px]">
        <div className="flex flex-wrap gap-1 justify-center">
          {variant.allergens && Array.isArray(variant.allergens) && variant.allergens.length > 0 ? (
            variant.allergens.map((allergen, idx) => (
              <span
                key={idx}
                className="inline-block px-2 py-0.5 bg-red-900/30 border border-red-500/50 rounded text-xs text-red-300"
              >
                {allergen}
              </span>
            ))
          ) : (
            <span className="text-xs text-gray-500">None</span>
          )}
        </div>
      </TableCell>

      {/* Allergen Notes - Editable text */}
      <EditableTableCell
        value={variant.allergen_notes || ''}
        type="text"
        isEditing={isCellEditing('allergen_notes')}
        onEdit={() => onEdit(index, 'allergen_notes')}
        onSave={(value) => onUpdate('allergen_notes', String(value))}
        onCancel={() => onEdit(-1, '')}
        placeholder="Notes..."
      />

      {/* Featured Toggle */}
      <TableCell className="w-16 text-center">
        <button
          type="button"
          onClick={() => onUpdate('featured', !(variant.featured ?? false))}
          className={cn(
            'text-2xl transition-all cursor-pointer',
            variant.featured ? 'text-yellow-400' : 'text-gray-600 hover:text-yellow-300'
          )}
          title={variant.featured ? 'Featured variant' : 'Mark as featured'}
        >
          ★
        </button>
      </TableCell>

      {/* Default Selection */}
      <TableCell className="w-24 text-center">
        <div className="flex justify-center">
          <button
            type="button"
            onClick={onSetDefault}
            className={cn(
              'h-5 w-5 rounded-full border-2 transition-all cursor-pointer',
              'hover:border-green-400',
              variant.is_default
                ? 'border-green-500 bg-green-500'
                : 'border-gray-400 bg-transparent'
            )}
            title={variant.is_default ? 'Default variant' : 'Set as default'}
          >
            {variant.is_default && (
              <div className="h-2 w-2 rounded-full bg-white m-auto" />
            )}
          </button>
        </div>
      </TableCell>

      {/* Delete Action */}
      <TableCell className="w-12">
        <Button
          variant="ghost"
          size="sm"
          onClick={onDelete}
          className="h-8 w-8 p-0 opacity-0 group-hover:opacity-100 transition-opacity hover:bg-red-500/20 hover:text-red-400"
          title="Delete variant"
        >
          <Trash2 className="h-4 w-4" />
        </Button>
      </TableCell>
    </TableRow>
  );
};

SortableVariantRow.displayName = 'SortableVariantRow';
